linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - gosec

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor
    - docs

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 