@baseUrl = http://localhost:8080
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzk4NTE2NjcsInVzZXJfaWQiOjEsInVzZXJuYW1lIjoiam9obl9kb2UxIn0.CFryzQLUUmDqTM5fvlfGb9VY07MeRUuV4fVUwcDk2tQ


### Регистрация пользователя
POST {{baseUrl}}/api/auth
Content-Type: application/json

{
    "username": "john_doe12",
    "password": "secure_password123"
}

### Получение информации о пользователе (баланс, история транзакций и покупок)
GET {{baseUrl}}/api/info
Authorization: Bearer {{accessToken}}

### Получение списка мерча
GET {{baseUrl}}/api/merch
Content-Type: application/json

### Получение мерча по ID
GET {{baseUrl}}/api/merch/10
Content-Type: application/json

### Покупка мерча
POST {{baseUrl}}/api/merch/buy
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "merch_id": 3,
    "quantity": 2
}

### Перевод монет другому пользователю
POST {{baseUrl}}/api/transactions/transfer
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "to_user_id": 2,
    "amount": 100,
    "description": "За обед"
}